### ISSUE TITLE
Install breaks with typing-extensions >= 4.6.0

### ISSUE THREAD

**Issue by makkus** [hashberg-io/multiformats#10]
It looks like the `typing-extensions` package released version `4.6.x` on May 23rd, and this breaks multiformats for me on any Python version older than 3.11.

Stacktrace is:
```
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/multiformats/multibase/__init__.py", line 22, in <module>
    from bases import (base2, base16, base8, base10, base36, base58btc, base58flickr, base58ripple,
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/bases/__init__.py", line 40, in <module>
    from . import encoding as encoding
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/bases/encoding/__init__.py", line 293, in <module>
    base8 = FixcharBaseEncoding(alphabet.base8, pad_char="=", padding="include")
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/bases/encoding/fixchar.py", line 106, in __init__
    validate(char_nbits, Union[int, Literal["auto"]])
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/typing_validation/validation.py", line 635, in validate
    _validate_union(val, t)
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/typing_validation/validation.py", line 515, in _validate_union
    validate(val, member_t)
  File "/home/markus/.local/share/micromamba/envs/kiara-mono/lib/python3.10/site-packages/typing_validation/validation.py", line 691, in validate
    raise unsupported_type_error
ValueError: Unsupported validation for type typing_extensions.Literal['auto'].
```
Pinning typing-extensions to `4.5.0` makes it work again...

**Comment by sg495** [comment]
The core issue appears to be with the `typing-validation` dependency (cf. https://github.com/hashberg-io/typing-validation/issues/1). We'll fix it shortly 😃.

**Comment by MarshalX** [comment]
> The core issue appears to be with the `typing-validation` dependency (cf. [hashberg-io/typing-validation#1](https://github.com/hashberg-io/typing-validation/issues/1)). We'll fix it shortly 😃.

any updates?

**Comment by snarfed** [comment]
* https://github.com/snarfed/bridgy-fed/pull/643
* https://github.com/snarfed/granary/pull/593

**Comment by Aviksaikat** [comment]
any update ?

**Comment by Aviksaikat** [comment]
Looks like we have to wait for a long time. I have created a fork here & published a pip package. feel free to open PRs :smile: 
https://github.com/aviksaikat/multiformats
https://pypi.org/project/multiformats-fix/

**Comment by makkus** [comment]
Ha, funny, I also created one two days ago ( https://github.com/makkus ):

- https://pypi.org/project/makkus.typing-validation/
- https://pypi.org/project/makkus.bases/
- https://pypi.org/project/makkus.multiformats/
- https://pypi.org/project/makkus.multiformats-config/

Available also via conda (dharpa channel). I forked all 4 projects because otherwise you end up with two 'typing-validation'  packages ('bases' also pulls it in).

**Comment by sg495** [comment]
This has now been fixed upstream, with my apologies for the long delay 🙏. A new version of typing_validation will be released shortly, after which I will proceed to close the remaining issues on this package and make a new release.

This package is now again in active development, so I welcome any PRs to include changes/fixed/improvements you may have made in your forks.

**Comment by sg495** [comment]
Update: [`typing_extensions==1.1.0`](https://pypi.org/project/typing-validation/1.1.0/) has now been released on PyPI. Will now run tests for `bases` and `multiformats`.

**Comment by snarfed** [comment]
Woo, these new releases are working great for me. Thank you @sg495! Hope you're doing ok. Welcome back!

**Comment by sg495** [comment]
Update: [`multiformats-config==0.3.0`](https://pypi.org/project/multiformats-config/0.3.0) has now been released on PyPI. Will now run tests for core `multiformats` package.

**Comment by sg495** [comment]
Thank you for your patience, everybody: [`multiformats==0.3.1`](https://pypi.org/project/multiformats/0.3.1) has now been released, closing all issues 🎉.

**Comment by sg495** [comment]
For those who were impacted on the DAG-CBOR side of things, [`dag-cbor==0.3.3`](https://pypi.org/project/dag-cbor/0.3.3) has now been released, closing a small validation issue and setting the minimum `multiformats` version to `0.3.1`. This issue is now fully solved.
