### ISSUE TITLE
Implementation difference of 'hash' type multiformat and 'multihash'

### ISSUE THREAD

**Issue by kralverde** [hashberg-io/multiformats#15]
I have been working on making a CAR block decoder in python as a personal project. When testing HAMT-shards, I got the exception: `multiformats.multihash.err.MultihashValueError: Multicodec 'murmur3-x64-64' exists, but it is not a multihash multicodec`.

It seems that the type of the murmur3 was recently changed to that of a 'hash' as it is not cryptographic (https://github.com/multiformats/multihash/issues/157).

Changing lines https://github.com/hashberg-io/multiformats/blob/99afd7690ae773ddb84091b4f984c7fe279bce67/multiformats/multihash/raw.py#L122 and https://github.com/hashberg-io/multiformats/blob/99afd7690ae773ddb84091b4f984c7fe279bce67/multiformats/multihash/__init__.py#L59 to allow the 'hash' type allowed me to hash normally with:

```
>>> from multiformats import multihash
>>> mh = multihash.get(code=0x22)
>>> mh.digest(b'test')
b'"\x08\x9a\x12\x821\xf9\xbdM\x82'
```

Should the 'hash' type be allowed with multihashes, or should something else be done with them?

**Comment by sg495** [comment]
Happy with those suggested changes, they have now been committed. I hope this helps you!
