### ISSUE TITLE
Option to parse `CID`

### ISSUE THREAD

**Issue by Aviksaikat** [hashberg-io/multiformats#17]
It would be nice to have an option to parse `CID`s like this https://github.com/multiformats/js-multiformats/blob/139b3c2fa0d1afcba9f0aafde929fcf69f4d7804/src/cid.js#L485

**Comment by sg495** [comment]
The documentation for [`CID.decode`](https://multiformats.readthedocs.io/en/latest/api/multiformats.cid.html#multiformats.cid.CID.decode) had a refuse from a previous implementation. It still said:

> Decodes a CID from a bytestring or a hex string (which will be converted to [bytes](https://docs.python.org/3/library/stdtypes.html#bytes) using [bytes.fromhex](https://docs.python.org/3/library/stdtypes.html#bytes.fromhex)). Note: the hex string is not multibase encoded.

While it should have said:

> Decodes a CID from a bytestring or a multibase-encoded string.

I have pushed the change and the documentation has been updated. Does this answer your question?

**Comment by Aviksaikat** [comment]
yes. Thanks. Also I was wondering if you would like to upgrade to `pyproject.toml` & change `pysha3` to `safe-pysha3` to support python3.11 & above ? Actually my fork is doing all of these already

**Comment by sg495** [comment]
Pull Request https://github.com/hashberg-io/multiformats/pull/16 yesterday removed the pysha3 dependency for keccak, in favour of `pycryptodomex` (which is already a dependency for other hash functions). Would you like to make one or more pull requests, so I can integrate other changes you've made?

**Comment by Aviksaikat** [comment]
Cool. I can make it use `pyproject.toml` & `black` + `ruff`

**Comment by sg495** [comment]
Happy to start with a migration to `pyproject.toml`. I am not used to `black` or `ruff`, but I am certainly open to consider a case in their favour. Perhaps the best way to proceed is to close this issue and open 3 new issues, one for each proposed upgrade, so we can tackle them incrementally?

**Comment by Aviksaikat** [comment]
cool. I'll open 2 issues then & closing this one
