### ISSUE TITLE
Can't reference most functions with intersphinx

### ISSUE THREAD

**Issue by johntruckenbrodt** [hashberg-io/multiformats#21]
Hi there,
I want to use `multiformats.multihash` in my code and reference some functions in the docs. However, this does not work for most functions except for those in the submodule `varint` from what I have tested.

works:
```
:mod:`multiformats.varint`
:func:`multiformats.varint.decode`
```

doesn't work:
```
:mod:`multiformats`
:mod:`multiformats.multihash`
:func:`multiformats.multihash.wrap`
```

I haven't gotten to the bottom of it but I am pretty sure it is because of the `api` subfolder of the documentation and the ambiguity between files like 
```
https://github.com/hashberg-io/multiformats/blob/main/docs/multihash.rst
https://github.com/hashberg-io/multiformats/blob/main/docs/api/multiformats.multihash.rst
```

Couldn't the structure of the `docs` folder be simplified by removing the `api` folder and integrating the API TOC elsewhere?  
Also, what is the purpose of the `intersphinx` folder? Why not just reference the `objects.inv` files coming with the respective readthedocs pages?

**Comment by sg495** [comment]
I just tested all your examples:

![image](https://github.com/hashberg-io/multiformats/assets/13587235/f4836694-2338-4e31-b7ff-4a50fb7cab25)

and for me they all compile correctly, linking to the respective pages of the multiformats docs:

![image](https://github.com/hashberg-io/multiformats/assets/13587235/f3d87aa8-8ec2-4fe4-86ad-9ac0e54211db)

I suspect this may be an issue with your configuration of intersphinx, or at the very least a difference between yours and ours. Would you mind sharing some additional details on how you configured intersphinx to connect to multiformats? For your reference, here is a snippet from the `conf.py` that I used when testing:

```py
intersphinx_cache_limit = -1
intersphinx_timeout = 20
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'multiformats': ('http://multiformats.readthedocs.io/en/latest', None)
}
```

**Comment by johntruckenbrodt** [comment]
Thanks for your reply and sorry for being a little too sure about the source of error. Using `latest` instead of `stable` does the trick:
```diff
- https://multiformats.readthedocs.io/en/stable
+ https://multiformats.readthedocs.io/en/latest
```
The docs for `stable` exist but are basically empty:
https://multiformats.readthedocs.io/en/stable/api/multiformats.multihash.html#multiformats.multihash.wrap

I see that the last build for `stable` failed:  
https://readthedocs.org/projects/multiformats/builds/

I would really prefer referencing the `stable` version. Could you perhaps issue a bug fix release so that the `stable` build succeeds?

For reference, here is my configuration:
https://github.com/SAR-ARD/s1ard/blob/feature/stac_asset_hash/docs/source/conf.py

**Comment by sg495** [comment]
I've done a new build of stable, you should be able to access it now!

**Comment by johntruckenbrodt** [comment]
Awesome! Thanks a lot @sg495.
