### ISSUE TITLE
`io.BufferedIOBase` or `typing.BinaryIO` ?

### ISSUE THREAD

**Issue by d70-t** [hashberg-io/multiformats#3]
Disclaimer: I'm kind of new to typing in Python.

`multiformats` makes heavy use of type information :+1:. However, I'm wondering if it should be `io.BufferedIOBase` or `typing.BinaryIO` ? Naively I'd say, the binary-ness is more important than the buffered-ness.

In particular, I came across a case where I wanted to read from a file and use the resulting object in `varint.decode`. As `varint.decode` requires `io.BufferedIOBase`, typecheking my code with `mypy` fails. 

Minimal example (e.g. `test` would be a function like `varint.decode` from the `multiformats` package):

This fails using `mypy --strict`:
```python
from io import BufferedIOBase, BytesIO

def test(stream: BufferedIOBase) -> None:
    pass

def main() -> None:
    with open("test.bin", "rb") as testfile:
        test(testfile)
    test(BytesIO(b"test"))
```

this version passes `mypy --strict`:
```python
from io import BytesIO
from typing import BinaryIO

def test(stream: BinaryIO) -> None:
    pass

def main() -> None:
    with open("test.bin", "rb") as testfile:
        test(testfile)
    test(BytesIO(b"test"))
```

**Comment by sg495** [comment]
Thanks @d70-t for this observation, and my apologies for the long wait in coming back to you. You raise a very good point: in the upcoming v0.1.4, both `typing.BinaryIO` and `io.BufferedIOBase` will be supported.
